language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t evgeniyp92/docker-react -f dockerfile.dev .

script:
  - docker run -e CI=true evgeniyp92/docker-react npm run test
